# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXvmJVpupIGFTi8Ma7zivv3b1bra56qm
"""

import networkx as nx
import matplotlib.pyplot as plt
import ast
from networkx.algorithms import community
from collections import Counter


# -----------------------------
# Load Graph
# -----------------------------
def load_graph(filepath):
    G = nx.DiGraph()

    with open(filepath, "r") as f:
        for line in f:
            parts = line.strip().split(maxsplit=2)
            node1, node2 = parts[0], parts[1]

            attr_dict = ast.literal_eval(parts[2])
            weight = attr_dict['weight']

            G.add_edge(node1, node2, weight=weight)

    return G


# -----------------------------
# Validate Graph
# -----------------------------
def validate_graph(G):
    print("\n=== Graph Summary ===")
    print("Nodes:", G.number_of_nodes())
    print("Edges:", G.number_of_edges())
    print("Directed:", G.is_directed())

    print("\nSample edges:")
    for u, v, d in list(G.edges(data=True))[:5]:
        print(u, v, d)


# -----------------------------
# Degree Analysis
# -----------------------------
def degree_analysis(G):
    print("\n=== Degree Analysis ===")

    degree = dict(G.degree())
    weighted_degree = dict(G.degree(weight='weight'))

    print("Top Degree:", sorted(degree.items(), key=lambda x: x[1], reverse=True)[:5])
    print("Top Weighted Degree:", sorted(weighted_degree.items(), key=lambda x: x[1], reverse=True)[:5])


# -----------------------------
# Centrality Analysis
# -----------------------------
def centrality_analysis(G):
    print("\n=== Centrality Analysis ===")

    def top_k(dic, k=5):
        return sorted(dic.items(), key=lambda x: x[1], reverse=True)[:k]

    deg = nx.degree_centrality(G)
    bet = nx.betweenness_centrality(G)
    close = nx.closeness_centrality(G)
    pr = nx.pagerank(G)

    print("Degree:", top_k(deg))
    print("Betweenness:", top_k(bet))
    print("Closeness:", top_k(close))
    print("PageRank:", top_k(pr))

    # weighted
    bet_w = nx.betweenness_centrality(G, weight='weight')
    close_w = nx.closeness_centrality(G, distance='weight')
    pr_w = nx.pagerank(G, weight='weight')

    print("\nWeighted Betweenness:", top_k(bet_w))
    print("Weighted Closeness:", top_k(close_w))
    print("Weighted PageRank:", top_k(pr_w))

    return deg, bet, close, pr


# -----------------------------
# Community Detection
# -----------------------------
def community_analysis(G):
    print("\n=== Community Analysis ===")

    communities = list(community.greedy_modularity_communities(G))
    community_list = [list(c) for c in communities]

    node_community = {}
    for i, comm in enumerate(community_list):
        for node in comm:
            node_community[node] = i

    print("Number of communities:", len(community_list))
    print("Community sizes:", Counter(node_community.values()))

    return community_list, node_community


# -----------------------------
# Bridge Analysis
# -----------------------------
def bridge_analysis(G, node_community, bet):
    print("\n=== Bridge Nodes ===")

    bridges = []

    for node, score in bet.items():
        neigh_comms = set(node_community.get(n) for n in G.neighbors(node))
        if len(neigh_comms) > 1:
            bridges.append((node, score))

    top_bridges = sorted(bridges, key=lambda x: x[1], reverse=True)[:10]

    for n, s in top_bridges:
        print(n, s)

    return [n for n, _ in top_bridges]


# -----------------------------
# Visualization
# -----------------------------
def visualize(G, node_community, bridge_nodes):
    print("\n=== Generating Visualizations ===")

    pos = nx.spring_layout(G, seed=42)
    colors = [node_community[n] for n in G.nodes()]

    # community plot
    plt.figure(figsize=(12, 8))
    nx.draw_networkx_nodes(G, pos, node_color=colors, cmap=plt.cm.tab20, node_size=30)
    nx.draw_networkx_edges(G, pos, alpha=0.2)
    plt.title("Community Structure")
    plt.axis("off")
    plt.savefig("outputs/community_plot.png")
    plt.close()

    # bridge highlight
    plt.figure(figsize=(12, 8))
    nx.draw_networkx_nodes(G, pos, node_color=colors, cmap=plt.cm.tab20, node_size=30, alpha=0.6)
    nx.draw_networkx_nodes(G, pos, nodelist=bridge_nodes, node_color="red", node_size=80)
    nx.draw_networkx_edges(G, pos, alpha=0.2)
    plt.title("Bridge Nodes Highlighted")
    plt.axis("off")
    plt.savefig("outputs/bridge_plot.png")
    plt.close()


# -----------------------------
# Robustness Analysis
# -----------------------------
def robustness_analysis(G, deg, bet, pr):
    print("\n=== Robustness Analysis ===")

    def top_k(dic, k=10):
        return sorted(dic.items(), key=lambda x: x[1], reverse=True)[:k]

    top_deg = set(n for n, _ in top_k(deg))
    top_bet = set(n for n, _ in top_k(bet))
    top_pr = set(n for n, _ in top_k(pr))

    print("Overlap Degree vs Betweenness:", len(top_deg & top_bet))
    print("Overlap Degree vs PageRank:", len(top_deg & top_pr))

    # connectivity
    print("\nConnectivity:")
    print("Weak components:", len(list(nx.weakly_connected_components(G))))
    print("Strong components:", len(list(nx.strongly_connected_components(G))))

    # node removal
    remove_nodes = [n for n, _ in top_k(bet, 5)]
    G2 = G.copy()
    G2.remove_nodes_from(remove_nodes)

    print("\nAfter removing top betweenness nodes:")
    print("Weak components:", len(list(nx.weakly_connected_components(G2))))


# -----------------------------
# MAIN
# -----------------------------
def main():
    G = load_graph("data/congress.edgelist.txt")

    validate_graph(G)
    degree_analysis(G)

    deg, bet, close, pr = centrality_analysis(G)

    community_list, node_community = community_analysis(G)

    bridge_nodes = bridge_analysis(G, node_community, bet)

    visualize(G, node_community, bridge_nodes)

    robustness_analysis(G, deg, bet, pr)


if __name__ == "__main__":
    main()